all:
	gcc -O counter_tests.c concurrent_data_structures.c -o counter_tests.o
	gcc -O linked_list_test.c concurrent_data_structures.c -o linked_list_test.o
	gcc -O queue_tests.c concurrent_data_structures.c -o queue_tests.o
